name: Pyinstaller

on:
  push:
    branches: [ master ]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test Build Python Exe
      uses: eric2788/pyinstaller-build@master
      with:
        main: main
        artifact: Program
        use-dependencies: true
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: LordOfTheMines_Linux
        path: dist
        
  build_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Build Python Exe
        uses: eric2788/pyinstaller-build@master
        with:
          main: main
          artifact: Program
          use-dependencies: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: LordOfTheMines_Win
          path: dist
